---
version: 2

project_name: gitree

force_token: github

before:
  hooks:
    - go mod tidy -diff
    - make lint
    - make test
    - make security
    - make build

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s
      - -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.buildTime={{ .Date }}
    main: ./cmd/gitree
    binary: ./cmd/gitree
    ignore:
      - goos: linux
        goarch: arm64

archives:
  - id: default
    name_template: >-
      {{- .ProjectName }}_ {{- .Version }}_ {{- .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end -}}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: LICENSE*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: README*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

homebrew_casks:
  - url:
      template: "https://github.com/andreygrechin/gitree/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    binaries: [cmd/gitree]
    directory: Casks
    caveats: |
      As part of the installation process, brew will automatically run the following command
      to remove the quarantine attribute:
        /usr/bin/xattr -dr com.apple.quarantine .../gitree
    homepage: "https://github.com/andreygrechin/gitree"
    description: "A CLI tool that scans directories for Git repos and displays them in a tree format with status information."
    license: "MIT"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cmd/gitree"]
          end
    skip_upload: auto
    repository:
      owner: andreygrechin
      name: homebrew-tap
      branch: main

sboms:
  - artifacts: archive

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot+{{ .ShortCommit }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums_SHA256.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  groups:
    - title: New features
      regexp: '^feat(\(.+\))??!?:.+$'
      order: 100
    - title: Security updates
      regexp: '^sec(\(.+\))??!?:.+$'
      order: 150
    - title: Bug fixes
      regexp: '^(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: Dependency updates
      regexp: '^deps(\(.+\))??!?:.+$'
      order: 300
    - title: Documentation updates
      regexp: '^docs?(\(.+\))??!?:.+$'
      order: 400
    - title: Build process updates
      regexp: '^(build|ci)(\(.+\))??!?:.+$'
      order: 400
    - title: Other work
      order: 9999
  filters:
    exclude:
      - "^.$"
      - '^test(\(.+\))??!?:.+$'

release:
  draft: true
  make_latest: false
  replace_existing_draft: true
  name_template: "gitree v{{ .Version }}"
  footer: |-
    **Full Changelog**: https://github.com/andreygrechin/gitree/compare/{{ .PreviousTag }}...{{ .Tag }}

signs:
  - artifacts: checksum
    args:
      - "-u"
      - "36399892+andreygrechin@users.noreply.github.com"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
